server:
  port: 8091
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka/
spring:
  application:
    name: feign
  thymeleaf:
    encoding: UTF-8
    servlet:
      content-type: text/html


