server:
  port: 8101
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka/

mybatis:
      mapper-locations: classpath*:mapper/*.xml


spring:
   application:
     name: service-market
   datasource:
     driverClassName: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/shixun?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
     username: root
     password: root
   jpa:
     database: mysql