server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka/
spring:
  application:
    name: provider
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/1808b?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Hongkong
    username: root
    password:
  thymeleaf:
    encoding: UTF-8
    servlet:
      content-type: text/html
mybatis:
  mapper-locations: classpath:mapper/*.xml